import { FC } from 'react';
import VideoHeader from './components/VideoHeader';


import './style.css';
import 'bootstrap/dist/css/bootstrap.min.css';

export const App: FC<{ name: string }> = ({ name }) => {
  return (
    <div className="App">
    <VideoHeader />

    <div className="container-fluid position-absolute w-100 h-100">
      <div className="row h-100">
        <div className="col-md-6 d-flex flex-column justify-content-center align-items-start p-5">
          <h1>Your Name</h1>
          <h3>Your Title</h3>
        </div>
        <div className="col-md-6 overflow-auto p-5">
          {/* Add a lot of content here to test scrolling */}
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vel elit scelerisque mauris pellentesque pulvinar. Augue neque gravida in fermentum. Eu lobortis elementum nibh tellus molestie. At tempor commodo ullamcorper a lacus vestibulum sed arcu. Phasellus egestas tellus rutrum tellus. Quisque id diam vel quam elementum pulvinar etiam non. Mauris pharetra et ultrices neque. Eros donec ac odio tempor orci. Et ultrices neque ornare aenean euismod elementum nisi quis. Lectus nulla at volutpat diam ut venenatis. Nisl nunc mi ipsum faucibus vitae. At quis risus sed vulputate odio.

Ut eu sem integer vitae justo. Pellentesque habitant morbi tristique senectus. Ullamcorper velit sed ullamcorper morbi tincidunt. Est placerat in egestas erat imperdiet sed euismod nisi. Nunc mattis enim ut tellus elementum sagittis vitae et leo. Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet. Sed id semper risus in hendrerit gravida. Aliquet enim tortor at auctor urna. Eu scelerisque felis imperdiet proin fermentum leo vel orci. Senectus et netus et malesuada fames ac. Diam vel quam elementum pulvinar. Quis hendrerit dolor magna eget est. Ipsum nunc aliquet bibendum enim facilisis gravida neque convallis a.

Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi tristique. Amet facilisis magna etiam tempor orci eu lobortis elementum. Nunc consequat interdum varius sit. Nisi est sit amet facilisis magna. Lectus urna duis convallis convallis tellus id. Purus ut faucibus pulvinar elementum. Habitant morbi tristique senectus et netus et malesuada. Integer vitae justo eget magna fermentum. Feugiat nibh sed pulvinar proin gravida hendrerit. Quis varius quam quisque id diam vel quam elementum. Duis ultricies lacus sed turpis tincidunt. Felis eget velit aliquet sagittis id consectetur purus ut faucibus. Augue eget arcu dictum varius duis at consectetur. Elit eget gravida cum sociis natoque.

Et molestie ac feugiat sed lectus vestibulum. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium. Sed vulputate odio ut enim blandit volutpat. Non arcu risus quis varius quam quisque. Fringilla ut morbi tincidunt augue interdum velit euismod in. Bibendum est ultricies integer quis auctor elit sed vulputate mi. Quis risus sed vulputate odio ut enim blandit. Ultricies lacus sed turpis tincidunt id aliquet risus. Vel fringilla est ullamcorper eget. Magna eget est lorem ipsum dolor sit amet. Elementum tempus egestas sed sed. Vitae proin sagittis nisl rhoncus. Vel facilisis volutpat est velit egestas dui. Urna cursus eget nunc scelerisque viverra. Sit amet consectetur adipiscing elit duis tristique sollicitudin. Ultrices dui sapien eget mi proin sed.

Risus at ultrices mi tempus imperdiet nulla malesuada pellentesque elit. Sed blandit libero volutpat sed cras ornare arcu. Etiam sit amet nisl purus in mollis nunc sed. Sed velit dignissim sodales ut eu. Turpis in eu mi bibendum. Eu scelerisque felis imperdiet proin fermentum leo. Turpis egestas maecenas pharetra convallis posuere morbi. Ut aliquam purus sit amet. Ornare lectus sit amet est placerat. Adipiscing at in tellus integer feugiat scelerisque varius. Ipsum dolor sit amet consectetur adipiscing elit. Consectetur libero id faucibus nisl tincidunt eget nullam non nisi. Aliquam eleifend mi in nulla posuere. Laoreet id donec ultrices tincidunt arcu. Ullamcorper sit amet risus nullam eget felis eget. Amet luctus venenatis lectus magna fringilla urna. Convallis tellus id interdum velit laoreet id donec ultrices tincidunt. Pellentesque sit amet porttitor eget dolor morbi non arcu. Pharetra pharetra massa massa ultricies mi quis.

Vestibulum lectus mauris ultrices eros. Sagittis id consectetur purus ut faucibus pulvinar. Sit amet venenatis urna cursus eget nunc scelerisque viverra mauris. Donec et odio pellentesque diam volutpat commodo. Suscipit adipiscing bibendum est ultricies integer quis auctor elit sed. Vitae justo eget magna fermentum iaculis eu. Elit ullamcorper dignissim cras tincidunt lobortis. Aliquet nec ullamcorper sit amet risus nullam eget. Fames ac turpis egestas integer eget aliquet. Enim tortor at auctor urna nunc. Donec adipiscing tristique risus nec feugiat in fermentum. Amet cursus sit amet dictum. Viverra nibh cras pulvinar mattis. Facilisi cras fermentum odio eu feugiat pretium. Quis hendrerit dolor magna eget est lorem ipsum dolor sit. Cursus in hac habitasse platea dictumst quisque sagittis purus. Ipsum dolor sit amet consectetur. In ornare quam viverra orci sagittis eu volutpat. Et leo duis ut diam. Sit amet justo donec enim diam vulputate ut.

Hac habitasse platea dictumst quisque sagittis purus. At urna condimentum mattis pellentesque. Enim eu turpis egestas pretium aenean. Enim ut tellus elementum sagittis vitae et. Magna fermentum iaculis eu non diam phasellus vestibulum. Vitae congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Urna condimentum mattis pellentesque id nibh tortor id aliquet. Dui accumsan sit amet nulla facilisi. Congue nisi vitae suscipit tellus mauris a diam. Arcu dictum varius duis at consectetur lorem donec massa.

Pellentesque elit eget gravida cum sociis natoque. Urna condimentum mattis pellentesque id nibh. Nunc vel risus commodo viverra maecenas accumsan lacus vel facilisis. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Adipiscing enim eu turpis egestas pretium. Volutpat blandit aliquam etiam erat. Arcu risus quis varius quam quisque. Id interdum velit laoreet id donec ultrices tincidunt arcu non. Nec feugiat nisl pretium fusce. Dolor morbi non arcu risus quis varius quam quisque. Blandit libero volutpat sed cras ornare arcu dui. Integer enim neque volutpat ac tincidunt vitae semper quis lectus. Vitae sapien pellentesque habitant morbi. Proin sagittis nisl rhoncus mattis rhoncus urna neque. Elit sed vulputate mi sit. Viverra nibh cras pulvinar mattis nunc sed blandit libero volutpat. Tempus quam pellentesque nec nam aliquam sem. Ac auctor augue mauris augue neque. Morbi tempus iaculis urna id.

Ultrices dui sapien eget mi proin sed libero. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Lobortis feugiat vivamus at augue eget. Sit amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Vitae elementum curabitur vitae nunc sed velit dignissim. Netus et malesuada fames ac. Venenatis cras sed felis eget velit aliquet sagittis id. Eros in cursus turpis massa tincidunt dui ut. Suspendisse in est ante in nibh. Id nibh tortor id aliquet lectus.

Ipsum faucibus vitae aliquet nec. Faucibus in ornare quam viverra. Nec dui nunc mattis enim ut tellus. Amet risus nullam eget felis eget. Erat imperdiet sed euismod nisi porta lorem mollis. Nisl vel pretium lectus quam id leo in vitae turpis. Sollicitudin aliquam ultrices sagittis orci. Et netus et malesuada fames ac turpis. Pellentesque elit eget gravida cum sociis natoque penatibus et. Sit amet tellus cras adipiscing enim eu. Risus quis varius quam quisque id diam vel. Vel turpis nunc eget lorem dolor. Vitae tortor condimentum lacinia quis. Facilisi cras fermentum odio eu feugiat. Et tortor consequat id porta nibh venenatis cras sed. Nec dui nunc mattis enim ut tellus elementum sagittis. Pulvinar elementum integer enim neque volutpat ac. Fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec. Amet cursus sit amet dictum.

Morbi tincidunt ornare massa eget egestas purus viverra. Neque egestas congue quisque egestas diam in arcu cursus euismod. Pharetra magna ac placerat vestibulum lectus. Enim nunc faucibus a pellentesque sit amet porttitor eget. Purus non enim praesent elementum facilisis leo vel. Amet luctus venenatis lectus magna. Dui id ornare arcu odio ut. Amet cursus sit amet dictum. Ut placerat orci nulla pellentesque dignissim enim sit. Orci sagittis eu volutpat odio. Risus ultricies tristique nulla aliquet. At in tellus integer feugiat scelerisque varius morbi enim nunc. Mattis ullamcorper velit sed ullamcorper morbi. Nunc id cursus metus aliquam eleifend mi in. Scelerisque eu ultrices vitae auctor eu. Pretium fusce id velit ut tortor pretium viverra suspendisse potenti. Augue lacus viverra vitae congue eu consequat ac felis. Sit amet justo donec enim diam vulputate ut. Semper eget duis at tellus at urna.

Sed risus pretium quam vulputate dignissim suspendisse. Feugiat vivamus at augue eget arcu dictum varius duis. Massa enim nec dui nunc mattis enim. Urna molestie at elementum eu facilisis. Ipsum dolor sit amet consectetur adipiscing. Lobortis feugiat vivamus at augue. Nibh tortor id aliquet lectus proin nibh nisl. Sit amet consectetur adipiscing elit duis. Amet nisl suscipit adipiscing bibendum. Aenean et tortor at risus viverra adipiscing at.

Diam sollicitudin tempor id eu nisl nunc. Ultricies tristique nulla aliquet enim tortor at. Velit euismod in pellentesque massa. Erat velit scelerisque in dictum non consectetur a erat. Facilisis magna etiam tempor orci eu. Varius morbi enim nunc faucibus a pellentesque sit amet porttitor. Dolor sit amet consectetur adipiscing elit duis tristique sollicitudin. Malesuada proin libero nunc consequat interdum varius sit. Lectus mauris ultrices eros in cursus. Ultrices gravida dictum fusce ut placerat orci. Diam maecenas sed enim ut. Donec adipiscing tristique risus nec feugiat in fermentum posuere. Auctor urna nunc id cursus. Ac tortor vitae purus faucibus. Urna neque viverra justo nec ultrices dui sapien eget. Luctus accumsan tortor posuere ac ut consequat semper viverra nam. Proin sagittis nisl rhoncus mattis rhoncus urna.

Nisl nisi scelerisque eu ultrices vitae. Et malesuada fames ac turpis egestas. Purus viverra accumsan in nisl nisi. Dictum fusce ut placerat orci nulla pellentesque. Nec dui nunc mattis enim ut. Elementum curabitur vitae nunc sed velit dignissim. Iaculis nunc sed augue lacus viverra vitae congue. Morbi enim nunc faucibus a pellentesque sit amet porttitor eget. Nunc faucibus a pellentesque sit. Odio ut sem nulla pharetra diam sit amet. Ultricies lacus sed turpis tincidunt id. Lorem sed risus ultricies tristique nulla aliquet enim tortor at. Non arcu risus quis varius quam. Duis at consectetur lorem donec massa sapien faucibus et molestie. Consectetur purus ut faucibus pulvinar elementum integer enim neque. Mauris ultrices eros in cursus turpis massa. Eu lobortis elementum nibh tellus molestie nunc non blandit massa. Sem et tortor consequat id porta nibh venenatis cras. Enim blandit volutpat maecenas volutpat blandit aliquam etiam erat velit.

Scelerisque eleifend donec pretium vulputate. Nunc sed blandit libero volutpat. Nibh tellus molestie nunc non blandit massa enim nec. Ut venenatis tellus in metus. Elit at imperdiet dui accumsan sit. Non tellus orci ac auctor augue mauris augue neque gravida. Semper eget duis at tellus at urna condimentum mattis pellentesque. Congue quisque egestas diam in arcu cursus euismod quis. Pharetra magna ac placerat vestibulum lectus mauris ultrices eros in. Eu scelerisque felis imperdiet proin. Fames ac turpis egestas sed tempus urna et. Gravida cum sociis natoque penatibus et. Netus et malesuada fames ac turpis egestas maecenas.

Faucibus interdum posuere lorem ipsum dolor sit amet consectetur adipiscing. Eu augue ut lectus arcu bibendum at varius vel. Diam sit amet nisl suscipit adipiscing. Nisl purus in mollis nunc sed. Bibendum neque egestas congue quisque egestas diam. Fames ac turpis egestas maecenas. Et magnis dis parturient montes nascetur ridiculus mus. Gravida quis blandit turpis cursus in hac habitasse platea dictumst. Lacus laoreet non curabitur gravida arcu ac tortor. Vulputate mi sit amet mauris commodo. Vitae suscipit tellus mauris a diam. Etiam erat velit scelerisque in dictum non.

Eleifend donec pretium vulputate sapien. Dignissim sodales ut eu sem. Sit amet aliquam id diam maecenas ultricies mi eget. Nunc eget lorem dolor sed viverra ipsum. Tincidunt dui ut ornare lectus sit amet est placerat in. Sed arcu non odio euismod lacinia at. Vitae tortor condimentum lacinia quis vel eros donec. Volutpat sed cras ornare arcu dui vivamus arcu. Tristique sollicitudin nibh sit amet. Sodales ut eu sem integer vitae justo eget magna fermentum. Eu volutpat odio facilisis mauris sit amet massa vitae. Feugiat vivamus at augue eget arcu. Vulputate enim nulla aliquet porttitor lacus luctus. Nunc vel risus commodo viverra maecenas accumsan lacus vel. Amet mattis vulputate enim nulla aliquet porttitor lacus. Laoreet id donec ultrices tincidunt arcu non sodales neque. Maecenas sed enim ut sem viverra aliquet eget. Aliquam id diam maecenas ultricies mi eget mauris pharetra. Non tellus orci ac auctor augue mauris augue neque. Cras tincidunt lobortis feugiat vivamus.

Sed enim ut sem viverra aliquet eget sit. Non blandit massa enim nec dui. Id cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Magna fermentum iaculis eu non diam. Faucibus turpis in eu mi bibendum neque egestas congue. Mauris ultrices eros in cursus turpis massa tincidunt dui. Vel elit scelerisque mauris pellentesque pulvinar. Fermentum iaculis eu non diam phasellus vestibulum lorem sed. Scelerisque varius morbi enim nunc faucibus. Amet nisl suscipit adipiscing bibendum est ultricies.

Montes nascetur ridiculus mus mauris vitae. Nec feugiat in fermentum posuere. Tincidunt eget nullam non nisi est. Risus in hendrerit gravida rutrum quisque. Etiam tempor orci eu lobortis. Scelerisque felis imperdiet proin fermentum leo vel orci porta. Turpis egestas pretium aenean pharetra magna. Ligula ullamcorper malesuada proin libero. Ipsum dolor sit amet consectetur. Volutpat consequat mauris nunc congue nisi vitae.

Lorem ipsum dolor sit amet. Felis donec et odio pellentesque diam volutpat commodo sed egestas. Varius duis at consectetur lorem donec massa sapien faucibus. Velit scelerisque in dictum non consectetur a erat. Quisque egestas diam in arcu cursus. Phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet enim. Quisque non tellus orci ac. Nisl condimentum id venenatis a. Ultrices neque ornare aenean euismod elementum nisi quis eleifend. Sagittis purus sit amet volutpat. Netus et malesuada fames ac turpis egestas integer eget.

Ultricies integer quis auctor elit sed vulputate mi. Proin fermentum leo vel orci porta non. Sit amet porttitor eget dolor morbi non arcu risus quis. Cras pulvinar mattis nunc sed blandit. Nunc sed velit dignissim sodales ut eu sem integer. Tristique senectus et netus et. Condimentum vitae sapien pellentesque habitant morbi tristique senectus. Nunc lobortis mattis aliquam faucibus purus in massa. Nec dui nunc mattis enim ut. Congue quisque egestas diam in. Donec adipiscing tristique risus nec feugiat in fermentum posuere.

Dolor sit amet consectetur adipiscing elit. Imperdiet nulla malesuada pellentesque elit eget gravida. Massa tempor nec feugiat nisl pretium fusce id. Etiam erat velit scelerisque in dictum non. Urna duis convallis convallis tellus id interdum velit laoreet id. Praesent tristique magna sit amet purus. Porttitor leo a diam sollicitudin tempor. Condimentum lacinia quis vel eros donec ac odio tempor orci. Varius morbi enim nunc faucibus a pellentesque sit amet. Curabitur gravida arcu ac tortor dignissim convallis aenean et tortor. Quis blandit turpis cursus in hac habitasse platea dictumst. Euismod lacinia at quis risus sed. Pretium fusce id velit ut. Convallis posuere morbi leo urna molestie at elementum eu facilisis. Aliquam nulla facilisi cras fermentum odio eu feugiat. Urna porttitor rhoncus dolor purus non enim praesent elementum.

Commodo nulla facilisi nullam vehicula ipsum a arcu cursus. Proin fermentum leo vel orci porta non. Convallis a cras semper auctor neque vitae tempus. Varius vel pharetra vel turpis nunc eget lorem. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. At consectetur lorem donec massa sapien faucibus et. Ipsum suspendisse ultrices gravida dictum fusce. Eget arcu dictum varius duis at consectetur lorem donec. Tempus iaculis urna id volutpat lacus laoreet non curabitur. Morbi tristique senectus et netus et malesuada fames ac turpis. Scelerisque varius morbi enim nunc. Orci eu lobortis elementum nibh tellus molestie nunc. Commodo elit at imperdiet dui accumsan sit.

A lacus vestibulum sed arcu non odio euismod lacinia at. Amet est placerat in egestas erat imperdiet sed euismod nisi. Congue nisi vitae suscipit tellus mauris a. Risus nec feugiat in fermentum. Mi quis hendrerit dolor magna eget est lorem ipsum dolor. Risus nec feugiat in fermentum posuere urna nec tincidunt. Duis at consectetur lorem donec massa sapien faucibus et molestie. Faucibus a pellentesque sit amet porttitor eget dolor morbi non. Cursus eget nunc scelerisque viverra mauris in aliquam sem fringilla. Odio euismod lacinia at quis. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies. Ornare suspendisse sed nisi lacus sed viverra. Id interdum velit laoreet id donec ultrices.

Turpis cursus in hac habitasse platea dictumst quisque. Fames ac turpis egestas sed tempus urna et pharetra. Gravida cum sociis natoque penatibus et magnis dis parturient montes. Tristique magna sit amet purus gravida quis blandit turpis. In tellus integer feugiat scelerisque varius morbi enim nunc. Dictum sit amet justo donec enim diam vulputate ut. Quam lacus suspendisse faucibus interdum. Cum sociis natoque penatibus et magnis dis. Elit scelerisque mauris pellentesque pulvinar. Nisl vel pretium lectus quam id. Fusce ut placerat orci nulla pellentesque dignissim. Turpis tincidunt id aliquet risus feugiat in ante.

In pellentesque massa placerat duis ultricies lacus sed turpis. Sit amet venenatis urna cursus. Sit amet volutpat consequat mauris. Et tortor consequat id porta nibh venenatis cras sed. Odio aenean sed adipiscing diam donec. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Fames ac turpis egestas sed tempus urna et. Pretium aenean pharetra magna ac placerat vestibulum lectus mauris ultrices. Eu turpis egestas pretium aenean pharetra magna. Diam quis enim lobortis scelerisque fermentum dui faucibus in ornare. Aliquam nulla facilisi cras fermentum. Sit amet luctus venenatis lectus. Purus in massa tempor nec feugiat nisl pretium fusce id. Praesent tristique magna sit amet purus gravida quis blandit turpis. Sapien faucibus et molestie ac. Volutpat est velit egestas dui id.

Elementum curabitur vitae nunc sed velit dignissim sodales. Ullamcorper eget nulla facilisi etiam. Gravida rutrum quisque non tellus orci ac auctor augue mauris. Nunc lobortis mattis aliquam faucibus purus in. Magna fringilla urna porttitor rhoncus dolor purus non. Pretium viverra suspendisse potenti nullam ac tortor. Dignissim suspendisse in est ante in. Nisi lacus sed viverra tellus in hac habitasse platea dictumst. Tempus urna et pharetra pharetra massa. Cras fermentum odio eu feugiat. Volutpat sed cras ornare arcu dui vivamus. Libero nunc consequat interdum varius sit amet mattis vulputate. Risus quis varius quam quisque id diam vel quam elementum. In aliquam sem fringilla ut morbi tincidunt. In iaculis nunc sed augue.

Dictum sit amet justo donec enim diam vulputate ut. Purus semper eget duis at tellus at. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Egestas purus viverra accumsan in nisl nisi scelerisque eu. Quis blandit turpis cursus in hac habitasse platea. Vehicula ipsum a arcu cursus vitae congue mauris rhoncus aenean. Purus semper eget duis at tellus at urna condimentum. Ut sem viverra aliquet eget sit amet. Elementum eu facilisis sed odio morbi quis commodo odio aenean. Pulvinar neque laoreet suspendisse interdum consectetur libero id faucibus nisl. Non diam phasellus vestibulum lorem sed risus. Sit amet nulla facilisi morbi.

Risus pretium quam vulputate dignissim suspendisse in est ante. Erat velit scelerisque in dictum non. Odio euismod lacinia at quis risus sed vulputate odio ut. Aliquam faucibus purus in massa tempor nec feugiat. Ac tincidunt vitae semper quis lectus nulla. Eu lobortis elementum nibh tellus. Imperdiet sed euismod nisi porta lorem mollis aliquam. Aenean sed adipiscing diam donec adipiscing tristique risus. Ac tortor vitae purus faucibus ornare suspendisse. Ornare quam viverra orci sagittis eu. Viverra justo nec ultrices dui sapien eget mi proin sed. Tortor pretium viverra suspendisse potenti nullam. Sit amet cursus sit amet dictum sit amet.

Vitae tempus quam pellentesque nec nam aliquam sem et tortor. Nulla facilisi etiam dignissim diam quis enim lobortis. Orci ac auctor augue mauris augue neque. Fermentum iaculis eu non diam. Suspendisse potenti nullam ac tortor vitae. Amet mauris commodo quis imperdiet. Nunc id cursus metus aliquam eleifend. Tristique senectus et netus et malesuada fames ac turpis. Ipsum suspendisse ultrices gravida dictum fusce ut. Nam aliquam sem et tortor.</p>
          {/* ... */}
        </div>
      </div>
    </div>
  </div>
);
}
 
